{{ if .Values.deployment.blue.enabled }}
{{ $context := dict "root" . "Slot" "blue" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-service-account.name" $context }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s.labelset" $context | nindent 4 }}
  {{- with .Values.deployment.blue.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{ if .Values.deployment.green.enabled }}
{{ $context := dict "root" . "Slot" "green" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-service-account.name" $context }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s.labelset" $context | nindent 4 }}
  {{- with .Values.deployment.green.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
